# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Linux Web App.
# Add steps that run tests and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'ff71ebfd-fd04-4e31-ae22-a652e3bd534d'  # Replace with correct subscription ID
  webAppName: 'imus-it-ticket-system'                        # Replace with correct app name
  environmentName: 'imus-it-ticket-system'
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
  - stage: Build
    displayName: 'Build Stage'
    variables:
      phpVersion: '8.2'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              sudo update-alternatives --set php /usr/bin/php$(phpVersion)
              sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
              sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
              sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
              sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
              php -v
            workingDirectory: $(rootFolder)
            displayName: 'Use PHP version $(phpVersion)'

          - script: composer install --no-interaction --prefer-dist --optimize-autoloader
            workingDirectory: $(rootFolder)
            displayName: 'Composer install'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(rootFolder)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            displayName: 'Upload package'
            artifact: drop

  - stage: Deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        displayName: 'Deployment Job'
        pool:
          vmImage: ubuntu-latest
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy Azure Web App : imus-it-ticket-system'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(webAppName)
                    appType: webAppLinux
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
