name: Build and deploy PHP app to Azure Web App - imus-it-ticket-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      # Uncomment this section if you use composer and are not committing vendor/
      # - name: Check if composer.json exists
      #   id: check_files
      #   uses: andstor/file-existence-action@v1
      #   with:
      #     files: 'composer.json'
      # - name: Run composer install if composer.json exists
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # --- ADD THIS AZURE LOGIN STEP ---
      - name: Azure Login
        uses: azure/login@v1 # Or @v2 if you prefer
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Reference the secret you created
      # ----------------------------------

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Add this if you have a startup.sh script
      - name: Make startup script executable
        run: chmod +x startup.sh 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'imus-it-ticket-system'
          slot-name: 'Production'
          package: .
          # You can often remove publish-profile if you use azure/login.
          # However, if your publish-profile secret is still needed for other reasons
          # or if the webapps-deploy action strictly requires it alongside azure/login,
          # you can keep it. Test without it first for cleaner setup.
          # publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8FF3D452A0BC49C4A9E65E73085AF2FD }}

          # Add this if you are using a startup.sh script for custom Nginx config
          startupCommand: /home/site/wwwroot/startup.sh